### PR TITLE
ci: Set up retroarch on Ubuntu runner

### LINKED ISSUE #41: Install RetroArch
#### Description

It's essential to test based on the directory structure of the original retropie. Try to install it on the Linux Ubuntu 20.04 system in the CI. If it fails, at least re-create the structure where the roms go.

** Important**: This has to be implemented after https://github.com/drpaneas/romie/issues/40 is completed

#### Acceptance Criteria

- [x] Install RetroArch

### PR DESCRIPTION
**Pull request by ge0r**
* Install retroarch on the Ubuntu runner through retroarch repository

* Run retroarch once so that config files are created

* Check that config dir is there

### CODE REVIEW

**Comment by ge0r** [comment]
I would like it if `ubuntu-20.04` is set as a variable (or an alias) since it is being used now in two places in the yaml.
Please enlighten me if you know how to do this : p

**Comment by zoispag** [comment]
LGTM 💪

**Review by zoispag — DISMISSED** [review]

**Comment by Anastasiadis** [comment]
LGTM

**Review by Anastasiadis — DISMISSED** [review]

**Comment by ge0r** [comment]
> I would like it if `ubuntu-20.04` is set as a variable (or an alias) since it is being used now in two places in the yaml.
> Please enlighten me if you know how to do this : p

So, I ended up using `if: startsWith(matrix.os,'ubuntu')` which seems like a good middle ground solution

**Review by zoispag — APPROVED** [review]
Perfect!

**Review by drpaneas — APPROVED** [review]
Thanks! Let's roll!

**Pull request merged**
