### PR TITLE
feat: Check if environment variable exists

### LINKED ISSUE #148: Check if an ENV var exists
**Dev story**
Write a function/method checks if an environment variable exists and returns its.

Example:
```go
homeDir, err := enVar("HOME")
```

**Acceptance Criteria**
- [ ] Use https://github.com/spf13/afero for filesystem abstraction
- [x] Make sure it works cross-platform
- [x] Put the function into `internal/utils` package
- [x] Make sure it's crossplatform
- [x] For logging use https://github.com/Sirupsen/logrus
- [x] Write a unit test
- [x] Make sure there are [testable examples](https://blog.golang.org/examples)

**Hints**:
* As an exercise, try to write the test first. Let it fail. Then try to fix it, by writing the actual implementation of the function.

**Extra Help**:
* https://gobyexample.com/environment-variables
* For logging https://linuxhint.com/golang-logrus-package/

**NOTICE**: If you are unable to mock this test, in worst case scenario, create a folder `internal/utils/testdata` and put actual files you can use for your test.

### PR DESCRIPTION
**Pull request by ge0r**
feat: Check if environment variable exists
Closes #148

### CODE REVIEW

**Review by drpaneas — DISMISSED** [review]
- Do not export functions that don't need to be exported (e.g. `argError` instead of `ArgError`), meaning they are used only within the package itself.

- Do not use `log.Error` if you return an error, but use `log.Debug` instead.

- Do not use abbreviations (e.g. `message` instead of `msg`).

- This `(err != nil) != tt.wantErr` is not readable. Please refactor.

- Test your function based on its inputs and outputs. Do not introduce your own (e.g. `wantErr bool`). Replace it with `wantErr`, since your function returns errors and check your errors. For example:

```go
func TestGetEnv(t *testing.T) {
	tests := []struct {
		name    string
		key     string
		want    string
		wantErr error
	}{
		{
			"Get environment variable that exists and has a value",
			"KEY_WITH_VALUE",
			"some random value",
			nil,
		},
		{
			"Get environment variable that exists but has empty value",
			"EMPTY_KEY",
			"",
			envVarError{"EMPTY_KEY", "environment variable is empty"},
		},
		{
			"Get environment variable that does not exist",
			"MISSING_KEY",
			"",
			envVarError{"MISSING_KEY", "environment variable not found"},
		},
		{
			"Receive empty key as argument",
			"",
			"",
			argError{"empty argument"},
		},
	}
	for _, tt := range tests {
		tt := tt

		if tt.key != "MISSING_KEY" { // should be really missing
			os.Setenv(tt.key, tt.want)
		}

		t.Run(tt.name, func(t *testing.T) {
			got, err := GetEnv(tt.key)
			fmt.Println(err)
			if got != tt.want || err != tt.wantErr {
				t.Errorf("GetEnv() = %v, %v want %v, %v", got, tt.want, err, tt.wantErr)
			}
		})
	}
}
```

**Comment by ge0r** [comment]
>     * Do not export functions that don't need to be exported (e.g. `argError` instead of `ArgError`), meaning they are used only within the package itself.
Yesterday we decided that this package's error implementation should follow closely [this](https://github.com/romie-gr/romie/pull/159/files) one for consistency, but I can go ahead and make the error types non exportable.
Moreover, my question here is, if another package is handling environment variables with functionality provided by the utils package, shouldn't it be able to throw a newly encountered utils.EnvVarError from there for instance?
<br>
>     * Do not use `log.Error` if you return an error, but use `log.Debug` instead.
All right! In which case should we use log.Error?
<br> 
>     * Do not use abbreviations (e.g. `message` instead of `msg`).
Done! 
<br>
>     * This `(err != nil) != tt.wantErr` is not readable. Please refactor.
> 
>     * Test your function based on its inputs and outputs. Do not introduce your own (e.g. `wantErr bool`). Replace it with `wantErr`, since your function returns errors and check your errors. For example:
> 
For both of these points, we agreed yesterday that I would use the boilerplate code for testing, as generated by vscode, both for clarity and consistency with error testing throughout the various packages (for now consistency between the `utils` and `archive` packages). So I left the code as was generated. 

In case we do not want to keep the generated code, which includes the `wantErr bool` check, I will go with your suggestion (although personally I would favor comparing error types instead of strings but this is too nit-picky).

> ```go
> func TestGetEnv(t *testing.T) {
> 	tests := []struct {
> 		name    string
> 		key     string
> 		want    string
> 		wantErr error
> 	}{
> 		{
> 			"Get environment variable that exists and has a value",
> 			"KEY_WITH_VALUE",
> 			"some random value",
> 			nil,
> 		},
> 		{
> 			"Get environment variable that exists but has empty value",
> 			"EMPTY_KEY",
> 			"",
> 			envVarError{"EMPTY_KEY", "environment variable is empty"},
> 		},
> 		{
> 			"Get environment variable that does not exist",
> 			"MISSING_KEY",
> 			"",
> 			envVarError{"MISSING_KEY", "environment variable not found"},
> 		},
> 		{
> 			"Receive empty key as argument",
> 			"",
> 			"",
> 			argError{"empty argument"},
> 		},
> 	}
> 	for _, tt := range tests {
> 		tt := tt
> 
> 		if tt.key != "MISSING_KEY" { // should be really missing
> 			os.Setenv(tt.key, tt.want)
> 		}
> 
> 		t.Run(tt.name, func(t *testing.T) {
> 			got, err := GetEnv(tt.key)
> 			fmt.Println(err)
> 			if got != tt.want || err != tt.wantErr {
> 				t.Errorf("GetEnv() = %v, %v want %v, %v", got, tt.want, err, tt.wantErr)
> 			}
> 		})
> 	}
> }
> ```

**Comment by drpaneas** [comment]
> Moreover, my question here is, if another package is handling environment variables with functionality provided by the utils package, shouldn't it be able to throw a newly encountered utils.EnvVarError from there for instance?
> 

since you return the error, the other package will be able to do whatever it likes with it. e.g.
```go
if homeDir, err := utils.GetEnv("HOME"); err != nil {
   log.Error(err) // this could be any of your errors
}
```

If we need in the future for some reason to export those some of those errors, we can always do it case by case.


> All right! In which case should we use log.Error?

When we want this message to be displayed to the user as an error message. Right now you are writing a library, you shouldn't take this decision, but leave the developer who's gonna use your library to decide what they want to with it. Since you are returning the error, the developer using your function can make up they mind how they would like to display this information to the user.

> For both of these points, we agreed yesterday that I would use the boilerplate code for testing, as generated by vscode, both for clarity and consistency with error testing throughout the various packages (for now consistency between the `utils` and `archive` packages). So I left the code as was generated.

I didn't know this was generated by vscode. In that case disregard my comment and don't change it.

**Comment by ggkioulis** [comment]
> > Moreover, my question here is, if another package is handling environment variables with functionality provided by the utils package, shouldn't it be able to throw a newly encountered utils.EnvVarError from there for instance?
> 
> since you return the error, the other package will be able to do whatever it likes with it. e.g.
> 
> ```go
> if homeDir, err := utils.GetEnv("HOME"); err != nil {
>    log.Error(err) // this could be any of your errors
> }
> ```
> 
> If we need in the future for some reason to export those some of those errors, we can always do it case by case.
> 
> > All right! In which case should we use log.Error?
> 
> When we want this message to be displayed to the user as an error message. Right now you are writing a library, you shouldn't take this decision, but leave the developer who's gonna use your library to decide what they want to with it. Since you are returning the error, the developer using your function can make up they mind how they would like to display this information to the user.
> 
> > For both of these points, we agreed yesterday that I would use the boilerplate code for testing, as generated by vscode, both for clarity and consistency with error testing throughout the various packages (for now consistency between the `utils` and `archive` packages). So I left the code as was generated.
> 
> I didn't know this was generated by vscode. In that case disregard my comment and don't change it.

**Comment by ge0r** [comment]
@drpaneas Thanks for the feedback and the advice! I think that the remaining issues have been tackled now.

**Review by zoispag — APPROVED** [review]

**Review by drpaneas — APPROVED** [review]
lgtm

**Comment by zoispag** [comment]
@mergify refresh

**Comment by zoispag** [comment]
@Mergifyio refresh

**Pull request merged**
