### PR TITLE
use the same configurations

### LINKED ISSUE #18: Same editorconfig
#### Description

Modern IDEs use different settings. In this project, all the maintainers are using heavily VSCode. As a result it makes sense to use the same configurations when it comes on doing many things related to syntax.

#### Acceptance Criteria

- [ ] If you are using VSCode, install https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig
- [ ] Apply the following `.editorconfig`

```config
root = true

[*]
end_of_line = lf
indent_size = 4
indent_style = tab
insert_final_newline = true
trim_trailing_whitespace = true
insert_final_newline = true
charset = utf-8

[*.{md,yml}]
indent_size = 2
indent_style = space
```

- [ ] Push it to the repo

### PR DESCRIPTION
**Pull request by cerebrux**
Just a proposal for fixing #18

### CODE REVIEW

**Review by drpaneas — CHANGES_REQUESTED** [review]
A couple of minor issues with the commit-msg:

1. It should start with an upper-case (e.g. `Use` instead of `use`).
2. You change only one file, that is I would prefer `configuration` instead of `configurations`. If you prefer to use plural, a better terms would be `settings`.
3. Make it more specific, e.g. _IDE configuration_
4. In the body section, please include `Fixes #18 `
5. In the body section, include the URL of the VSCode plugin that uses this configuration.

As for the actual content of this, let me ping @ktsamis @JohnGavr @GrSoul as well

**Review by drpaneas — CHANGES_REQUESTED** [review]
The comments are superfluous, please remove them, they are not needed.
Also, please squash your commits into one [1] 

[1] https://www.internalpointers.com/post/squash-commits-into-one-git

**Comment by drpaneas** [comment]
I've checked the settings in my vscode. Personally I am fine with the changes proposed. Just squash your commits into one and we are ready to go.

**Comment by cerebrux** [comment]
> I've checked the settings in my vscode. Personally I am fine with the changes proposed. Just squash your commits into one and we are ready to go.

Thanks for the squashing experience ! Never had to use it but now I love it. You should consider adding it as a skill

**Pull request merged**
