### PR TITLE
ci: add semantic.yml for semantic commits

### LINKED ISSUE #22: Bot checks for conventional commits
#### Description

It is essential we all have the same guideline/principle for pushing commit messages. Having a bot to ensure that will slow down the speed of an unorganised team and it will speed up the organised one.

#### Acceptance Criteria

- [x] Read and understand https://www.conventionalcommits.org/en/v1.0.0/
- [x] Now create and configure this [Semantic probot](https://github.com/zeke/semantic-pull-requests) for the repo 

Complexity: 2

### PR DESCRIPTION
**Pull request by Anastasiadis**
Addition of a yml file in .github/workflows in order to configure how commits should be phrased.

Current configuration:

1) ALL commits should always be semantic. Valid tokens are:
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert
2) PR titles can be or not be semantic. No rules for them. 
3) **merge:** and **revert:** commits are allowed too.

Closes #22

### CODE REVIEW

**Review by zoispag — COMMENTED** [review]
I would argue not to check each commit message separately. Especially if we do not have a pre-commit hook, I can foresee that we will push non-semantic valid commits, actions will _fail_ and we will have to rebase again and again. 😝 

Instead, I recommend enforcing semantic PR titles and **only** allowing "Squash and merge" of PRs. That way, we ensure a clean list of commits on master and will make the process of auto-generating release notes even easier.

**Review by drpaneas — CHANGES_REQUESTED** [review]
See the comment of @zoispag

**Comment by Anastasiadis** [comment]
@drpaneas @zoispag only titles of mrs are now checked. They should be semantic, and valid tokens remain the ones mentioned in comment #1.

**Review by drpaneas — APPROVED** [review]
Thanks Bill

**Review by zoispag — APPROVED** [review]

**Comment by zoispag** [comment]
@drpaneas is the bot installed?

**Pull request merged**
